# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=70)),
                ('MOBILE', models.IntegerField()),
                ('AGE', models.IntegerField()),
                ('CITY', models.CharField(max_length=100)),
            ],
        ),
    ]
